name: CICD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  compile:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.0

      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: self-hosted
    needs: compile

    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo yum install -y wget
          sudo rpm --import https://aquasecurity.github.io/trivy-repo/rpm/public.key
          sudo wget https://aquasecurity.github.io/trivy-repo/rpm/releases/trivy.repo -O /etc/yum.repos.d/trivy.repo
          sudo yum install -y trivy

      - name: Trivy Filesystem Scan
        run: trivy fs --format table -o fs-report.json .

      - name: Install Gitleaks
        run: |
          sudo yum install -y wget
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Gitleaks Code Scan
        run: gitleaks detect --source . -r gitleaks-report.json -f json
